version: '3.5'
services:
    api:
      container_name: "ct-api-develop"
      build:
        context: .
        dockerfile: ./docker/go-app-develop/Dockerfile
      ports:
        - 8080:8080
      environment:
        GO_WORK_DIR: "${GO_PROJECT_DIR}"
    postgres:
      container_name: ct-mph-postgres-dev
      build: "./docker/postgres"
      ports:
        - 5432:5432
      environment:
        - POSTGRES_DB=mphclub
        - POSTGRES_USER=mphclub
        - POSTGRES_PASSWORD=mphclub123
