// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// APIErrorDetail Api error detail
// swagger:model ApiErrorDetail
type APIErrorDetail struct {

	// end user message
	EndUserMessage string `json:"endUserMessage,omitempty"`

	// error code
	ErrorCode string `json:"errorCode,omitempty"`

	// error properties
	ErrorProperties interface{} `json:"errorProperties,omitempty"`
}

// Validate validates this Api error detail
func (m *APIErrorDetail) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIErrorDetail) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIErrorDetail) UnmarshalBinary(b []byte) error {
	var res APIErrorDetail
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
