// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Booking Booking Object containing details of a regeistered booking
// swagger:model Booking
type Booking struct {

	// confirmation number
	ConfirmationNumber string `json:"confirmationNumber,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// vehicle
	Vehicle *Vehicle `json:"vehicle,omitempty"`
}

// Validate validates this booking
func (m *Booking) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateVehicle(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Booking) validateVehicle(formats strfmt.Registry) error {

	if swag.IsZero(m.Vehicle) { // not required
		return nil
	}

	if m.Vehicle != nil {
		if err := m.Vehicle.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("vehicle")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Booking) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Booking) UnmarshalBinary(b []byte) error {
	var res Booking
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
