// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// EmailSendRequest email send request
// swagger:model EmailSendRequest
type EmailSendRequest struct {

	// body
	Body string `json:"body,omitempty"`

	// from email address
	FromEmailAddress string `json:"fromEmailAddress,omitempty"`

	// subject
	Subject string `json:"subject,omitempty"`

	// to email address
	ToEmailAddress string `json:"toEmailAddress,omitempty"`
}

// Validate validates this email send request
func (m *EmailSendRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EmailSendRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EmailSendRequest) UnmarshalBinary(b []byte) error {
	var res EmailSendRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
