// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// TemplatedEmailSendRequest templated email send request
// swagger:model TemplatedEmailSendRequest
type TemplatedEmailSendRequest struct {

	// email address
	EmailAddress string `json:"emailAddress,omitempty"`

	// Provide a key<string>-value<string> map of elements to distill into the email template
	Fields interface{} `json:"fields,omitempty"`

	// language locale
	LanguageLocale string `json:"languageLocale,omitempty"`

	// The templateId identifies which template
	TemplateID string `json:"templateId,omitempty"`
}

// Validate validates this templated email send request
func (m *TemplatedEmailSendRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TemplatedEmailSendRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TemplatedEmailSendRequest) UnmarshalBinary(b []byte) error {
	var res TemplatedEmailSendRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
