// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// VerifyAccount verify account
// swagger:model VerifyAccount
type VerifyAccount struct {

	// code
	Code string `json:"code,omitempty"`

	// username
	Username string `json:"username,omitempty"`
}

// Validate validates this verify account
func (m *VerifyAccount) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *VerifyAccount) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VerifyAccount) UnmarshalBinary(b []byte) error {
	var res VerifyAccount
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
